"""Reproducible search behind the absence claims of APP-01, APP-03 and APP-09 (Regulation S-X captions).

    uv run python scripts/sec_xcheck/absence_search.py [--sources DIR] [--log PATH]

Searches each Regulation S-X file for the terms below (case-insensitive, whole-word start, over the PDF's extracted
text with whitespace collapsed) and writes ``docs/checklist_sec/sec_xcheck/absence_search_log.md``: file, SHA-256,
term, hit count and the first hits in context. Articles 7 and 9 are the absence claims; Article 5 is the positive
contrast. Needs ``pypdf``.
"""

from __future__ import annotations

import argparse
import glob
import hashlib
import logging
import re
import sys
from pathlib import Path

if __package__ in (None, ""):
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from sec_xcheck.common import REPO, sources_dir

DEFAULT_LOG = REPO / "docs" / "checklist_sec" / "sec_xcheck" / "absence_search_log.md"
FILES = [
    "D2_RegSX_5-02",
    "D2_RegSX_5-03",
    "D3_RegSX_7-03",
    "D3_RegSX_7-04",
    "D4_RegSX_9-03",
    "D4_RegSX_9-04",
]
TERMS = [
    "current",
    "noncurrent",
    "non-current",
    "cost of goods",
    "cost of sales",
    "cost of revenue",
    "cost of tangible goods",
    "costs and expenses applicable to sales",
]
READING = [
    "",
    "**Reading of the hits** (reviewed by hand, 2026-10-08):",
    "- Articles 7 (7-03, 7-04) and 9 (9-03, 9-04): no current/noncurrent classification and no cost-of-sales "
    'caption. The single "current" hit in 9-04 is "current amortization of premium", not a classification.',
    '- Article 5: 5-03 has the caption "Costs and expenses applicable to sales and revenues" (cost of tangible '
    "goods sold, cost of services). The 5-02 file is an annual-print extract that also carries the start of 5-03 "
    'on its p.5; its classification captions are "Current Assets, when appropriate" and "Current Liabilities, '
    'When Appropriate" (quoted in APP-09).',
]


def search_pages(pages: list[str], term: str) -> list[tuple[int, str]]:
    """``(page, context)`` of every whole-word-start hit of *term* in the collapsed page texts."""
    return [
        (k + 1, t[max(0, m.start() - 40) : m.end() + 40])
        for k, t in enumerate(pages)
        for m in re.finditer(r"\b" + re.escape(term), t, re.IGNORECASE)
    ]


def build_log(docs: Path) -> list[str]:
    import pypdf  # noqa: PLC0415 - optional dependency, needed only to read the PDFs

    logging.disable(logging.CRITICAL)
    out = [
        "# Absence search log (project evidence, not a source)",
        "",
        "Generated by `scripts/sec_xcheck/absence_search.py`. An absence cannot be quoted, so the search itself is "
        "the evidence for the notes of APP-01, APP-03 and APP-09. Rules 5-02 and 5-03 (Article 5) are the "
        "positive contrast.",
        "",
        "| File | SHA-256 (first 16) | Term | Hits | First hits in context |",
        "|---|---|---|---|---|",
    ]
    for prefix in FILES:
        (path,) = glob.glob(str(docs / (prefix + "*")))
        sha = hashlib.sha256(Path(path).read_bytes()).hexdigest()[:16]
        pages = [re.sub(r"\s+", " ", p.extract_text() or "") for p in pypdf.PdfReader(path).pages]
        for term in TERMS:
            hits = search_pages(pages, term)
            ctx = " · ".join(f"p.{p}: …{c}…" for p, c in hits[:2]).replace("|", "/")
            out.append(f"| {prefix} | `{sha}` | {term} | {len(hits)} | {ctx} |")
    return [*out, *READING]


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--sources", help="directory of the source documents (SEC_XCHECK_SOURCES)")
    parser.add_argument("--log", default=str(DEFAULT_LOG), help="where to write the log")
    args = parser.parse_args(argv)
    lines = build_log(sources_dir(args.sources))
    Path(args.log).write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("\n".join(lines))
    return 0


if __name__ == "__main__":
    sys.exit(main())
