"""The defect map of T-147: every known defect to the checklist rules it breaks, with its measured extent and its task.

* ``OPEN``: D1-D10 (``reply_checklist_v1.md`` §3.6 and §4), N1-N18 (``code_comparison_v1.md`` §2) and the four the audit
  adds: N19 (the ``cost``/``costs`` label regex), N20 (T-140's ICE rebuild), N21 (10-Ks lost to a repeated period label
  or to a recorded gateway failure) and N22 (an oil & gas fallback tier that displaces a filer's real capex line; found by
  the review of PR #127).
* ``FIXED``: every defect of ``docs/model_fixes.md`` (F1, F2, C2, T-0xx, ...) and the rules it supports.
* ``UNCOVERED``: fixed defects no checklist rule covers (portfolio construction, quant, provenance).

``evidence`` lists finding keys of ``prevalence_results.json``; ``verdict`` is what the measurement says of the claim.
"""

from __future__ import annotations

# (id, defect, rules, evidence keys, verdict, task)
OPEN: list[tuple[str, str, str, tuple[str, ...], str, str]] = [
    (
        "D1",
        "Display sign stored instead of the filed sign (edgartools preferred_sign)",
        "ID-12, ID-11",
        ("src.income_tax.FLIPPED", "src.cogs.FLIPPED", "src.interest_expense.FLIPPED"),
        "confirmed, far larger than the pilot: income tax in 1,237 production filings (134 companies), COGS 211, interest 1,639; capex is displayed negative in 4,351",
        "T-148",
    ),
    (
        "D2",
        "Tier 2 takes the first document-order row: a label or wider concept beats the exact one",
        "ID-02a, ID-03",
        ("D2.equity_not_narrowest", "D2.net_income_profitloss_over_parent"),
        "confirmed: 38 filings read the wrong equity row; net income includes NCI in 2,247 filings (263 companies)",
        "T-148",
    ),
    (
        "D3",
        "income_tax standard-concept match picks a component when the total is absent",
        "ID-02b",
        ("D3.income_tax_component", "D6c.tax_current_deferred_without_total"),
        "confirmed: 55 filings of 9 companies resolve income tax to a component; current + deferred are both filed without a total only for APA (19 filings)",
        "T-148",
    ),
    (
        "D4",
        "short_term_debt reads one partial line",
        "ID-02b, MET-07",
        ("D4.short_term_debt_order_differs", "src.D4"),
        "confirmed: D-06(d)'s order changes 344 filings (53 companies); two or more short-term debt concepts are filed at the source in many more",
        "T-148",
    ),
    (
        "D5",
        "FUNDAMENTAL normalized_score is rewritten by every cycle (a decision, not a bug)",
        "—",
        (),
        "not a checklist matter; recorded in T-144's docs",
        "—",
    ),
    (
        "D6",
        "Stored valuation multiplies as-reported shares by a split-adjusted close",
        "MKT-02, MKT-01",
        ("MKT04.shares_not_from_cover_page",),
        "not re-measured (production's 258 valuation filings are metrics-v2 and use a balance-sheet or diluted count)",
        "T-148",
    ),
    (
        "D7",
        "REIT capex misses development and acquisition concepts",
        "APP-04b",
        ("APP04b.reit_acquisitions_left_out", "MET08.cause.reit_components"),
        "confirmed: 121 REIT filings file an acquisition line the capex excludes",
        "T-148",
    ),
    (
        "D8",
        "REIT tax rate: the 21% default against the actual ~0",
        "APP-04c, MET-03",
        ("APP04c.reit_tax_rate_21pct",),
        "confirmed: 125 of 314 REIT filings use the default (15 companies)",
        "T-151",
    ),
    (
        "D9",
        "Growth from a negative base has the wrong sign",
        "MET-04",
        (
            "MET04.net_income_growth_base_nonpositive",
            "MET04.free_cash_flow_growth_base_nonpositive",
        ),
        "confirmed: net income growth from a base <= 0 in 394 filings (167 companies)",
        "T-151 (absorbs T-076)",
    ),
    (
        "D10",
        "EV treats missing debt and cash as 0",
        "MET-00",
        ("D10.ev_debt_or_cash_zero_filled", "D10.ev_zero_filled_stored"),
        "confirmed: a term is missing in 4,994 filing-columns' filings; 81 of 258 stored valuations",
        "T-148",
    ),
    (
        "W1",
        "XOM's CIK in universe.db is the holding company; its filings are the predecessor's",
        "APP-10a, APP-10b",
        ("N1.stored_not_in_submissions",),
        "data correct (fetched by ticker); the audit follows the predecessor CIK",
        "T-149",
    ),
    (
        "N1",
        "A 10-K/A replaces (or, being statement-less, loses) the original 10-K",
        "PER-02, L-04",
        ("N1.stored_is_amendment", "N1.select_amendment_same_fy", "N1.missing_cause.amendment"),
        "confirmed on the SEC history: 55 company-years, 8 stored amendments, 48 originals missing",
        "T-149",
    ),
    (
        "N2",
        "earnings_yield is never computed",
        "MET-05, MET-00",
        ("N2.metrics_named_net_income", "N2.valorization_value_factor_null"),
        "confirmed: no metric of that name; the value factor is empty in 35 of 40 stored rows",
        "T-149",
    ),
    (
        "N3",
        "Operating cash flow resolves to the continuing-operations line",
        "CON-08, ID-02b",
        ("N3.ocf_continuing_resolved", "src.N3"),
        "confirmed and wider than measured: 34 companies, 191 filings once the YTD pair and prior are counted (F2)",
        "T-148",
    ),
    (
        "N4",
        "Debt double counting (LongTermDebt incl. current maturities plus LongTermDebtCurrent)",
        "MET-07, ID-02b",
        ("N4.debt_double_count", "src.N4"),
        "confirmed but small: 7 companies (25 filings) in the resolver, 22 at the source",
        "T-148",
    ),
    (
        "N5",
        "Cash double counting (cash + short-term investments, then investments again)",
        "ID-02a, ID-02b",
        ("N5.cash_double_count", "src.N5"),
        "confirmed but small: one company (CMI)",
        "T-148",
    ),
    (
        "N6",
        "Balance-sheet values from another date",
        "ID-05",
        ("N6.balance_from_other_date",),
        "confirmed but rare: 8 filings, 7 companies",
        "T-148",
    ),
    (
        "N7",
        "Missing components treated as 0 (debt, invested capital, EV)",
        "MET-00, ID-02b",
        ("N7.lt_debt_only", "N7.st_debt_only", "N7.debt_absent"),
        "confirmed: 4,988 filings have no debt line at all; 1,211 long-term only; 85 short-term only",
        "T-148 (D-01)",
    ),
    (
        "N8",
        "Financial firms vetoed on metrics that do not apply to them",
        "APP-02, APP-02b",
        ("N8.financial_firms_hard_vetoed", "F5.article9_vetoed_by_missing_revenue"),
        "partly borne out: 14 of 51 financial firms are vetoed, but LEVERAGE_EXTREME fires on none (D/E counts debt lines only); the vetoes are NEGATIVE_FCF (3) and DQ_REVENUE_POS (10)",
        "T-071 / T-148",
    ),
    (
        "N9",
        "Net cash with positive EBITDA discarded",
        "MET-09",
        ("N9.net_cash_positive_ebitda",),
        "confirmed: 177 filings, 63 companies",
        "T-151",
    ),
    (
        "N10",
        "effective_tax_rate shows 21% when pre-tax income <= 0",
        "MET-03, L-05",
        ("N10.tax_rate_21_on_nonpositive_pretax", "N10.tax_rate_21_on_loss"),
        "confirmed: 743 filings (172 companies); 283 on a loss",
        "T-151",
    ),
    (
        "N11",
        "Duplicate facts passed through unflagged",
        "ID-21",
        (),
        "gateway repo; source prevalence incomplete",
        "gateway PR",
    ),
    (
        "N12",
        "Four registry concepts are dead (declared in no 2020-2026 release)",
        "ID-20",
        ("src.N12.dead_concept_facts_ours", "src.N12.dead_concept_facts_all_history"),
        "confirmed and harmless in the window: no fact of ours uses them; the last historical use was filed 2021-11-22",
        "T-148 (cleanup)",
    ),
    (
        "N13",
        "Parent earnings fall back to NetIncomeLossAvailableToCommonStockholdersBasic",
        "ID-03",
        ("N13.net_income_available_to_common",),
        "confirmed: 83 filings, 15 companies; DECIDE",
        "T-148",
    ),
    (
        "N14",
        "D&A can be Depreciation alone",
        "ID-02b",
        ("N14.da_depreciation_alone", "src.N14"),
        "confirmed: 878 filings (95 companies) in the resolver, 142 companies at the source",
        "T-148",
    ),
    (
        "N15",
        "ROIC used with invested capital <= 0; ROE with negative equity",
        "APP-07",
        ("N15.roic_on_nonpositive_capital", "N15.roe_on_negative_equity"),
        "confirmed: 74 and 316 filings",
        "T-151",
    ),
    (
        "N16",
        "FUNDAMENTAL fallback score starts at 50",
        "MET-00",
        ("N16.fundamental_fallback_scores",),
        "confirmed but rare in the stored data: 1 of 377",
        "T-073",
    ),
    (
        "N17",
        "Winsorizing with few assets trims one value per tail (5% at n = 20)",
        "DQ-02",
        ("DQ02.winsor_2pct_vs_half_pct_stored", "DQ02.winsor_2pct_vs_half_pct_universe"),
        "confirmed: identical at n = 20; 245 of 495 assets move by more than a point at n = 495",
        "T-071",
    ),
    (
        "N18",
        "T-148's text contradicts ID-11 and cites no source for its maps",
        "ID-11, ID-02b",
        (),
        "task text; amended in this PR (D-06)",
        "T-148 (text)",
    ),
    (
        "N19",
        "T-140/T-117's total-label exclusion matches `cost` but not `costs`: a cost total reads as a revenue anchor",
        "ID-02b, CON-11",
        ("L09.refused_but_resolver_returns_a_value",),
        "16 ADP columns anchored on `TOTAL COSTS OF REVENUES`; the guard refuses them (the resolver keeps ADP's true revenue), so no derived value rests on a cost anchor today. Separately, BNY has 33 refused rebuilds anchored on `Total fee revenue` and no revenue at all (F5)",
        "T-148",
    ),
    (
        "N20",
        "T-140 derives wrong revenue for ICE (net-revenue anchor); it also fires for PSX, NI and MPC, not only APA",
        "ID-02b, L-09",
        ("L09.expost_fails.ICE", "L09.derived_by_company"),
        "17 ICE values; all 5 checkable ones fail the ex-post audit (derived 1,235M against 2,387M for 2022Q3). Under D-03b a value that fails the audit is left empty",
        "T-148 (high)",
    ),
    (
        "N21",
        "10-Ks lost to a repeated period label (52/53-week filers) or to a recorded gateway failure",
        "PER-02, PER-08, ID-08",
        (
            "N1.missing_cause.label_collision",
            "N1.missing_cause.recorded_error",
            "N1.missing_cause.unexplained",
        ),
        "9 labels collided (AVY, CDNS, DPZ, JNJ, RVTY, SNA, SWK, TDY, TXT): T-140's fix, absent from this database; 3 gateway failures (GEHC, CSCO, SMCI); 2 unexplained (EXE: a FY2021 10-K stored as FY2020; SMCI FY2024)",
        "rebuild (T-143); T-149 for EXE",
    ),
    (
        "N22",
        "The oil & gas fallback tiers fire before the caption fallback, so a gas-field line displaces the filer's real capital-expenditures line (DOW) or a zero oil & gas line hides a filed PP&E-family line (KKR)",
        "MET-08, ID-02b",
        (
            "N22.og_tier_displaces_capex_line",
            "N22.og_tier_with_ppe_family_line",
            "N22.og_tier_with_capex_caption",
            "N22.ppe_family_resolved_by_caption",
            "N22.ppe_family_capex_absent",
        ),
        "DOW FY2025 (0001751788-26-000018): 0.157B (`PaymentsToExploreAndDevelopOilAndGasProperties`, 'Investment in gas field developments') resolved against 2.479B filed as `PaymentsToAcquireMachineryAndEquipment` ('Capital expenditures'), so free cash flow is overstated by about 2.3B (DOW's five 10-Ks, FY2021 to FY2025: 1.4B to 2.7B a year). KKR's FY2021 and FY2022 10-Ks resolve 0 from a zero `PaymentsToExploreAndDevelopOilAndGasProperties` beside 0.10B and 0.09B of `PaymentsToAcquireFurnitureAndFixtures`. The caption fallback would not rescue it: the 'Cash flow hedging related to capital expenditures' row also matches, and the fallback refuses two captions. Filings whose capex is one of `PaymentsToAcquireMachineryAndEquipment`, `...OtherProductiveAssets`, `...OtherPropertyPlantAndEquipment` or `...FurnitureAndFixtures` (outside the registry) reach the right value only through the caption fallback, unflagged, at ADP, BAX, CPT, INCY, INVH, ROP, RL, VTR, VZ, WDAY and WEC; at COIN, DAL, HOOD, LNT, RF, ARES, EQIX, IP, LLY, VICI, EXR and KKR a filing of that kind resolves no capex at all",
        "T-148(f)",
    ),
]

# model_fixes.md entry -> (rules it supports, note)
FIXED: list[tuple[str, str, str]] = [
    (
        "F1 (T-103 residual)",
        "ID-18, A-03, PER-01",
        "share-count scale; T-103 made the evidence point in time. The rule says quarantine; the code still corrects",
    ),
    (
        "F2 (T-102, T-095, T-117, T-128)",
        "ID-02b, CON-11, ID-16, ID-09",
        "revenue concept resolution; total-concept plausibility; the utility total concept",
    ),
    (
        "F4 (T-094, T-105, T-133)",
        "PER-06, PER-08, ID-08, ID-06, MET-01, MET-02",
        "10-Q flow/stock mismatch; fiscal-calendar alignment; year-to-date identity",
    ),
    ("C2 (T-116)", "APP-07, MET-09", "negative-equity leverage evasion; the distress screen"),
    ("T-065", "Annex A (A-01 to A-05), CON", "Ring-1 DQ gates"),
    ("T-096", "PER-02, PER-06, PER-08", "10-Q filing gaps"),
    ("T-102", "CON-11, ID-20", "utilities' total operating revenue"),
    (
        "T-106, T-107",
        "PER-01",
        "cycle read filings before they were filed; no publication timestamp",
    ),
    ("T-113", "MET-00", "a rule-based fallback score stored under the LLM's name"),
    ("T-115", "PER-10", "cycle backfill replays history with the point-in-time universe"),
    ("T-119", "MET-00", "an unscored asset escaped every rule check"),
    ("T-131", "MKT-02", "price ingestion integrity (partial session, half-adjusted split)"),
    (
        "T-132",
        "MKT-01, MKT-03, MKT-04",
        "market cap: shares issued, unbounded-age cap, silent zero weight, period-end price",
    ),
    (
        "T-140",
        "ID-08, PER-08, L-09",
        "a revenue total the gateway dropped; filings lost to a repeated period label",
    ),
]

UNCOVERED: list[tuple[str, str]] = [
    ("C1 (T-1 veto cutoff)", "cycle policy: the veto lag is a portfolio rule, not a data rule"),
    ("Q2, Q3 (quant evaluation, dividends)", "quant package, outside the SEC data path"),
    ("T-097 (out-of-order cycle guard)", "cycle book integrity"),
    (
        "T-108, T-109, T-110, T-111, T-112 (quant return, mu, as-of past the price spine, missing asset-day, collapsed frontier)",
        "quant/price integrity",
    ),
    ("T-114 (dirty working tree)", "provenance"),
    ("T-125 (veto lifecycle)", "cycle policy"),
    ("T-134 to T-139 (portfolio weight rule)", "portfolio construction"),
]
